#!/usr/bin/env python3
"""Run a public-safe synthetic performance comparison for scan QC paths."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

from PIL import Image, ImageDraw


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
SUMMARY_JSON = "synthetic_performance_comparison.json"
REGRESSION_SIGNAL_OPERATIONS = (
    "deskew",
    "trim_dark_border",
    "auto_crop",
    "despeckle",
    "normalize_tones",
    "lighten_edge_shadow",
    "lighten_background_stains",
    "lighten_fold_shadows",
    "clean_bleed_through",
    "lighten_scanlines",
    "enhance_faded_text",
    "sharpen_text_edges",
)
DESPECKLE_BACKEND_MODES = ("numpy", "fallback", "not_applicable", "unknown")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="run_synthetic_performance_comparison.py",
        description="Create synthetic images and run public-safe benchmark variants.",
    )
    parser.add_argument("--out", required=True, type=Path, help="Output directory for synthetic data and summaries.")
    parser.add_argument("--image-count", default=8, type=_positive_int)
    parser.add_argument("--workers-list", default="1,2", help="Comma-separated worker counts for comparable runs.")
    parser.add_argument("--repeats", default=1, type=_positive_int)
    parser.add_argument("--width", default=640, type=_positive_int)
    parser.add_argument("--height", default=900, type=_positive_int)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        summary = run_synthetic_comparison(args)
    except (OSError, ValueError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"run_synthetic_performance_comparison.py: error: {exc}\n")
    print(f"Synthetic comparison summary: {args.out.resolve() / SUMMARY_JSON}")
    decision = summary["production_decision"]
    print(f"Production decision: {decision['worth_implementing_next'] or 'none'} - {decision['reason']}")
    return 0


def run_synthetic_comparison(args: argparse.Namespace) -> dict[str, Any]:
    output_dir = args.out.resolve()
    input_dir = output_dir / "synthetic-input"
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_synthetic_images(input_dir, args.image_count, args.width, args.height)

    variants = [
        {
            "id": "pillow_cpu_baseline",
            "label": "Current Python/Pillow CPU baseline",
            "benchmark_args": [
                "--auto-crop",
                "--deskew",
                "--trim-dark-border",
                "--despeckle",
                "--despeckle-backend",
                "fallback",
                "--reuse-scan-measurements",
                "--lighten-fold-shadows",
            ],
        },
        {
            "id": "numpy_vectorized_hotspots",
            "label": "NumPy vectorized despeckle hotspot when available",
            "benchmark_args": [
                "--auto-crop",
                "--deskew",
                "--trim-dark-border",
                "--despeckle",
                "--despeckle-backend",
                "numpy",
                "--reuse-scan-measurements",
                "--lighten-fold-shadows",
            ],
        },
    ]
    variant_summaries = []
    for variant in variants:
        benchmark_dir = output_dir / variant["id"]
        process_dir = benchmark_dir / "processed"
        command = [
            sys.executable,
            "-m",
            "archive_scan_qc.cli",
            "benchmark",
            "--input",
            str(input_dir),
            "--out",
            str(benchmark_dir),
            "--process-out",
            str(process_dir),
            "--workers-list",
            args.workers_list,
            "--repeats",
            str(args.repeats),
            *variant["benchmark_args"],
        ]
        subprocess.run(command, check=True, cwd=REPO_ROOT, env=_env())
        benchmark = json.loads((benchmark_dir / "benchmark_results.json").read_text(encoding="utf-8"))
        variant_summaries.append(_variant_summary(variant, benchmark))

    summary = {
        "schema_version": "scan-qc.synthetic-performance-comparison.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "privacy": {
            "public_safe": True,
            "input_source": "synthetic images generated by this script",
            "private_puersai_images_used": False,
        },
        "synthetic_input": {
            "image_count": args.image_count,
            "width": args.width,
            "height": args.height,
        },
        "variants": variant_summaries,
        "comparison_plan": variant_summaries[0]["comparison_plan"] if variant_summaries else None,
        "production_decision": _production_decision(variant_summaries),
    }
    (output_dir / SUMMARY_JSON).write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return summary


def _positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("value must be a positive integer.") from exc
    if parsed < 1:
        raise argparse.ArgumentTypeError("value must be a positive integer.")
    return parsed


def _env() -> dict[str, str]:
    env = dict(**__import__("os").environ)
    env["PYTHONPATH"] = str(SRC_DIR)
    return env


def _write_synthetic_images(input_dir: Path, image_count: int, width: int, height: int) -> None:
    input_dir.mkdir(parents=True, exist_ok=True)
    for stale in input_dir.glob("*.png"):
        stale.unlink()
    for index in range(1, image_count + 1):
        image = Image.new("RGB", (width, height), "white")
        draw = ImageDraw.Draw(image)
        margin = 42 + (index % 5)
        draw.rectangle((margin, margin, width - margin, height - margin), outline=(35, 35, 35), width=3)
        for line_index in range(12):
            y = margin + 42 + line_index * 44
            draw.line((margin + 28, y, width - margin - 28, y + (index % 3) - 1), fill=(55, 55, 55), width=2)
        for speckle_index in range(80):
            x = (speckle_index * 37 + index * 19) % width
            y = (speckle_index * 53 + index * 23) % height
            image.putpixel((x, y), (0, 0, 0))
        image.save(input_dir / f"synthetic_page_{index:03d}.png", dpi=(300, 300))


def _variant_summary(variant: dict[str, Any], benchmark: dict[str, Any]) -> dict[str, Any]:
    processing = benchmark["recommendations"].get("processing")
    best_processing_rate = processing["files_per_minute"] if processing else None
    latest_run = benchmark["runs"][-1] if benchmark["runs"] else {}
    return {
        "id": variant["id"],
        "label": variant["label"],
        "benchmark_schema_version": benchmark["schema_version"],
        "run_count": len(benchmark["runs"]),
        "best_processing_images_per_minute": best_processing_rate,
        "best_requested_workers": processing["best_requested_workers"] if processing else None,
        "failures": latest_run.get("processing", {}).get("failed_files"),
        "review_needed_counts": latest_run.get("finding_severity_counts", {}),
        "operation_timing_regression_signal": _operation_timing_regression_signal(benchmark),
        "quality_difference_summary": (
            "Synthetic aggregate comparison only; inspect deltas in failures and review-needed counts before "
            "using private orchestrator evidence."
        ),
        "environment": benchmark["environment"],
        "comparison_plan": benchmark["comparison_plan"],
    }


def _operation_timing_regression_signal(benchmark: dict[str, Any]) -> dict[str, Any]:
    runs = benchmark.get("runs")
    if not isinstance(runs, list):
        runs = []

    operations = {
        operation: _aggregate_operation_timing(runs, operation) for operation in REGRESSION_SIGNAL_OPERATIONS
    }
    missing_operations = [
        operation for operation, timing in operations.items() if not timing["signal_available"]
    ]
    return {
        "schema_version": "scan-qc.synthetic-operation-timing-regression-signal.v1",
        "source": "benchmark_results.runs.processing.operation_timings",
        "aggregate_only": True,
        "required_operations": list(REGRESSION_SIGNAL_OPERATIONS),
        "signal_available": not missing_operations,
        "missing_operations": missing_operations,
        "operations": operations,
        "privacy": {
            "contains_file_names": False,
            "contains_paths": False,
            "contains_hashes": False,
            "contains_thumbnails": False,
            "contains_ocr_text": False,
            "contains_row_level_evidence": False,
            "contains_image_content": False,
        },
    }


def _aggregate_operation_timing(runs: list[Any], operation: str) -> dict[str, Any]:
    elapsed_seconds = 0.0
    file_count = 0
    run_count = 0
    enabled_values: list[bool] = []
    reused_scan_measurement_files = 0
    deskew_safe_skip_files = 0
    deskew_projection_detection_files = 0
    deskew_fallback_detection_files = 0
    backend_counts = {mode: 0 for mode in DESPECKLE_BACKEND_MODES}

    for run in runs:
        if not isinstance(run, dict):
            continue
        processing = run.get("processing")
        if not isinstance(processing, dict):
            continue
        operation_timings = processing.get("operation_timings")
        if not isinstance(operation_timings, dict):
            continue
        timing = operation_timings.get(operation)
        if not isinstance(timing, dict):
            continue
        run_count += 1
        if isinstance(timing.get("enabled"), bool):
            enabled_values.append(timing["enabled"])
        elapsed = timing.get("elapsed_seconds")
        if isinstance(elapsed, int | float):
            elapsed_seconds += float(elapsed)
        count = timing.get("file_count")
        if isinstance(count, int):
            file_count += count
        reused = timing.get("reused_scan_measurement_files")
        if isinstance(reused, int):
            reused_scan_measurement_files += reused
        if operation == "deskew":
            safe_skip = timing.get("safe_skip_files")
            if isinstance(safe_skip, int):
                deskew_safe_skip_files += safe_skip
            projection = timing.get("projection_detection_files")
            if isinstance(projection, int):
                deskew_projection_detection_files += projection
            fallback = timing.get("fallback_detection_files")
            if isinstance(fallback, int):
                deskew_fallback_detection_files += fallback
        if operation == "despeckle":
            source_counts = timing.get("backend_counts")
            if isinstance(source_counts, dict):
                for mode in DESPECKLE_BACKEND_MODES:
                    value = source_counts.get(mode)
                    if isinstance(value, int):
                        backend_counts[mode] += value

    if run_count == 0:
        missing = {
            "signal_available": False,
            "missing_reason": "missing_from_benchmark_processing_operation_timings",
            "run_count": 0,
            "file_count": 0,
            "elapsed_seconds": 0.0,
            "files_per_minute": 0.0,
            "average_seconds_per_file": None,
            "reused_scan_measurement_files": 0,
        }
        if operation == "deskew":
            missing.update(
                {
                    "safe_skip_files": 0,
                    "projection_detection_files": 0,
                    "fallback_detection_files": 0,
                }
            )
        return missing

    elapsed_seconds = round(elapsed_seconds, 6)
    summary = {
        "signal_available": True,
        "enabled": any(enabled_values) if enabled_values else True,
        "run_count": run_count,
        "file_count": file_count,
        "elapsed_seconds": elapsed_seconds,
        "files_per_minute": _files_per_minute(file_count, elapsed_seconds),
        "average_seconds_per_file": round(elapsed_seconds / file_count, 6) if file_count else None,
        "reused_scan_measurement_files": reused_scan_measurement_files,
    }
    if operation == "deskew":
        summary.update(
            {
                "safe_skip_files": deskew_safe_skip_files,
                "projection_detection_files": deskew_projection_detection_files,
                "fallback_detection_files": deskew_fallback_detection_files,
            }
        )
    if operation == "despeckle":
        active_modes = [mode for mode in DESPECKLE_BACKEND_MODES if backend_counts[mode]]
        if len(active_modes) == 1:
            backend_mode = active_modes[0]
        elif active_modes:
            backend_mode = "mixed"
        else:
            backend_mode = "unknown"
        summary.update(
            {
                "backend_mode": backend_mode,
                "numpy_available": backend_counts["numpy"] > 0,
                "backend_counts": backend_counts,
            }
        )
    return summary


def _files_per_minute(file_count: int, elapsed_seconds: float) -> float:
    if elapsed_seconds <= 0:
        return 0.0
    return round((file_count / elapsed_seconds) * 60, 2)


def _production_decision(variants: list[dict[str, Any]]) -> dict[str, Any]:
    measured = [variant for variant in variants if variant["best_processing_images_per_minute"] is not None]
    if not measured:
        return {"worth_implementing_next": None, "reason": "No processing variants produced throughput metrics."}
    best = max(measured, key=lambda variant: variant["best_processing_images_per_minute"])
    baseline = next((variant for variant in measured if variant["id"] == "pillow_cpu_baseline"), None)
    if baseline and best["id"] != baseline["id"]:
        gain = best["best_processing_images_per_minute"] - baseline["best_processing_images_per_minute"]
        return {
            "worth_implementing_next": best["id"] if gain > 0 else None,
            "reason": (
                f"{best['label']} led synthetic processing throughput by {gain:.2f} images/min; "
                "confirm with private aggregate validation before implementation."
            ),
        }
    return {
        "worth_implementing_next": "pillow_cpu_baseline_worker_tuning",
        "reason": "The baseline was the best synthetic result; use worker tuning before adding new dependencies.",
    }


if __name__ == "__main__":
    raise SystemExit(main())
